### ISSUE TITLE
Map creation documentation does not refer to Nucleoid Creator Tools

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/nucleoid-docs#1]
Map creation documentation is written as if Plasmid provides functionality for maps to be built and exported. However, as of Plasmid 0.5, this is handled by a separate library, [Nucleoid Creator Tools](https://github.com/NucleoidMC/nucleoid-creator-tools).

For example, the export path uses `plasmid/exports` instead of `nucleoid_creator_tools/export`:

https://github.com/NucleoidMC/nucleoid-docs/blob/8a8ab2912e06b30eba1db5c766eb287906a5edcb/docs/plasmid/maps.md#L81

**Comment by Hugman76** [comment]
This has been fixed in the following commit: https://github.com/NucleoidMC/nucleoid-docs/commit/f07352c5cc7f7434b4ea689359a75b3a7e3d8970
